#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : librevenge
Version  : 0.0.5
Release  : 6
URL      : https://dev-www.libreoffice.org/src/librevenge-0.0.5.tar.bz2
Source0  : https://dev-www.libreoffice.org/src/librevenge-0.0.5.tar.bz2
Summary  : API library for generic document converters
Group    : Development/Tools
License  : LGPL-2.1 MPL-2.0-no-copyleft-exception
Requires: librevenge-lib = %{version}-%{release}
Requires: librevenge-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-configure
BuildRequires : doxygen
BuildRequires : file
BuildRequires : pkgconfig(cppunit)
BuildRequires : pkgconfig(zlib)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
librevenge is a base library for writing document import filters. It has
interfaces for text documents, vector graphics, spreadsheets and presentations.

%package dev
Summary: dev components for the librevenge package.
Group: Development
Requires: librevenge-lib = %{version}-%{release}
Provides: librevenge-devel = %{version}-%{release}
Requires: librevenge = %{version}-%{release}

%description dev
dev components for the librevenge package.


%package doc
Summary: doc components for the librevenge package.
Group: Documentation

%description doc
doc components for the librevenge package.


%package lib
Summary: lib components for the librevenge package.
Group: Libraries
Requires: librevenge-license = %{version}-%{release}

%description lib
lib components for the librevenge package.


%package license
Summary: license components for the librevenge package.
Group: Default

%description license
license components for the librevenge package.


%prep
%setup -q -n librevenge-0.0.5
cd %{_builddir}/librevenge-0.0.5
pushd ..
cp -a librevenge-0.0.5 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719970840
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --disable-werror
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --disable-werror
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719970840
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/librevenge
cp %{_builddir}/librevenge-%{version}/COPYING.LGPL %{buildroot}/usr/share/package-licenses/librevenge/3704f4680301a60004b20f94e0b5b8c7ff1484a9 || :
cp %{_builddir}/librevenge-%{version}/COPYING.MPL %{buildroot}/usr/share/package-licenses/librevenge/9744cedce099f727b327cd9913a1fdc58a7f5599 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/librevenge-0.0/librevenge-generators/RVNGCSVSpreadsheetGenerator.h
/usr/include/librevenge-0.0/librevenge-generators/RVNGHTMLTextGenerator.h
/usr/include/librevenge-0.0/librevenge-generators/RVNGRawDrawingGenerator.h
/usr/include/librevenge-0.0/librevenge-generators/RVNGRawPresentationGenerator.h
/usr/include/librevenge-0.0/librevenge-generators/RVNGRawSpreadsheetGenerator.h
/usr/include/librevenge-0.0/librevenge-generators/RVNGRawTextGenerator.h
/usr/include/librevenge-0.0/librevenge-generators/RVNGSVGPresentationGenerator.h
/usr/include/librevenge-0.0/librevenge-generators/RVNGTextDrawingGenerator.h
/usr/include/librevenge-0.0/librevenge-generators/RVNGTextPresentationGenerator.h
/usr/include/librevenge-0.0/librevenge-generators/RVNGTextSpreadsheetGenerator.h
/usr/include/librevenge-0.0/librevenge-generators/RVNGTextTextGenerator.h
/usr/include/librevenge-0.0/librevenge-generators/librevenge-generators-api.h
/usr/include/librevenge-0.0/librevenge-generators/librevenge-generators.h
/usr/include/librevenge-0.0/librevenge-stream/RVNGDirectoryStream.h
/usr/include/librevenge-0.0/librevenge-stream/RVNGStream.h
/usr/include/librevenge-0.0/librevenge-stream/RVNGStreamImplementation.h
/usr/include/librevenge-0.0/librevenge-stream/librevenge-stream-api.h
/usr/include/librevenge-0.0/librevenge-stream/librevenge-stream.h
/usr/include/librevenge-0.0/librevenge/RVNGBinaryData.h
/usr/include/librevenge-0.0/librevenge/RVNGDrawingInterface.h
/usr/include/librevenge-0.0/librevenge/RVNGPresentationInterface.h
/usr/include/librevenge-0.0/librevenge/RVNGProperty.h
/usr/include/librevenge-0.0/librevenge/RVNGPropertyList.h
/usr/include/librevenge-0.0/librevenge/RVNGPropertyListVector.h
/usr/include/librevenge-0.0/librevenge/RVNGSVGDrawingGenerator.h
/usr/include/librevenge-0.0/librevenge/RVNGSpreadsheetInterface.h
/usr/include/librevenge-0.0/librevenge/RVNGString.h
/usr/include/librevenge-0.0/librevenge/RVNGStringVector.h
/usr/include/librevenge-0.0/librevenge/RVNGTextInterface.h
/usr/include/librevenge-0.0/librevenge/librevenge-api.h
/usr/include/librevenge-0.0/librevenge/librevenge.h
/usr/lib64/librevenge-0.0.so
/usr/lib64/librevenge-generators-0.0.so
/usr/lib64/librevenge-stream-0.0.so
/usr/lib64/pkgconfig/librevenge-0.0.pc
/usr/lib64/pkgconfig/librevenge-generators-0.0.pc
/usr/lib64/pkgconfig/librevenge-stream-0.0.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/librevenge/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/librevenge-0.0.so.0.0.5
/V3/usr/lib64/librevenge-generators-0.0.so.0.0.5
/V3/usr/lib64/librevenge-stream-0.0.so.0.0.5
/usr/lib64/librevenge-0.0.so.0
/usr/lib64/librevenge-0.0.so.0.0.5
/usr/lib64/librevenge-generators-0.0.so.0
/usr/lib64/librevenge-generators-0.0.so.0.0.5
/usr/lib64/librevenge-stream-0.0.so.0
/usr/lib64/librevenge-stream-0.0.so.0.0.5

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/librevenge/3704f4680301a60004b20f94e0b5b8c7ff1484a9
/usr/share/package-licenses/librevenge/9744cedce099f727b327cd9913a1fdc58a7f5599
